name: lirx
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/One-Nub/lirx

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  toml: ^0.14.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
