# Example toml command layout based on Discord's example.

name = "blep"
description = "Send a random adorable animal photo"
type = 1

[[options]]
    name = "animal"
    description = "The type of animal"
    type = 3
    required = true
    choices = [
        {name = "Dog", value = "animal_dog"},
        {name = "Cat", value = "animal_cat"},
        {name = "Penguin", value = "animal_penguin"}
    ]

[[options]]
    name = "only_smol"
    description = "Whether to show only baby animals"
    type = 5
    required = false
